version: '3.9'

networks:
  default:
    driver: bridge

services:

  manager_php-fpm:
    domainname: ${DOMAIN}
    hostname: ${DOMAIN}
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    ports:
      - '9010:9010'
    volumes:
      - ./../app:/app:rw
    networks:
      - default
    depends_on:
      manager_redis:
        condition: service_started
      manager_db:
        condition: service_healthy
    working_dir: /app

  manager_supervisor:
    domainname: ${DOMAIN}
    hostname: ${DOMAIN}
    working_dir: /app
    build:
      context: ./supervisor
      dockerfile: Dockerfile
    restart: always
    depends_on:
      manager_redis:
        condition: service_started
      manager_db:
        condition: service_healthy
    volumes:
      - ./../app:/app:rw
      - ./supervisor/conf.d:/etc/supervisor/conf.d
      - ./supervisor/log:/var/log/supervisor

  manager_php-cli:
    domainname: ${DOMAIN}
    hostname: ${DOMAIN}
    working_dir: /app
    build:
      context: ./php-cli
      dockerfile: Dockerfile
    command: bash -c "sleep 10 && composer install"
    depends_on:
      manager_redis:
        condition: service_started
      manager_db:
        condition: service_healthy
    volumes:
      - ./../app:/app:rw

  manager_nginx:
    domainname: ${DOMAIN}
    hostname: ${DOMAIN}
    image: nginx:1.25.4
    ports:
      - "80:80"
      - "443:8443"
    networks:
      - default
    depends_on:
      - manager_php-fpm
    volumes:
      - ./../app:/app:rw
      - ./nginx/logs:/var/log/nginx:rw
      - ./nginx/hosts:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/ssl

  manager_redis:
    domainname: ${DOMAIN}
    hostname: ${DOMAIN}
    working_dir: /app
    image: redis:7.2.1
    restart: always
    volumes:
      - ./redis/data/:/data:rw

  manager_db:
    image: postgres:16.0-alpine3.17
    shm_size: 128mb
    restart: always
    networks:
      - default
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    command: [ "postgres", "-c", "logging_collector=on", "-c", "log_directory=/var/lib/postgresql/data/pg_log", "-c", "log_filename=postgresql.log", "-c", "log_statement=all" ]

volumes:
  nginx_log:
  app_log:
  db:
    driver: local
